In [2]:
#importing necessary libraries

import numpy
import tensorflow
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.layers import Conv2D
from keras.optimizers import Adam
from keras.utils import np_utils

In [3]:
#load data

(x_train, y_train), (x_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 6s 1us/step


In [4]:
print(x_train.shape)
print(x_test.shape)

(60000, 28, 28)
(10000, 28, 28)


In [5]:
#understanding the data

x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [6]:
y_train[0]

5

In [8]:
y_train.shape

(60000,)

In [10]:
x_test.shape

(10000, 28, 28)

In [11]:
#Reshaoing the Dataset

x_train = x_train.reshape(60000, 28, 28, 1).astype('float32')
x_test = x_test.reshape(10000, 28, 28, 1).astype('float32')

In [13]:
#One-Hot Encoding

number_of_classes = 10
y_train = np_utils.to_categorical(y_train, number_of_classes)
y_test = np_utils.to_categorical(y_test, number_of_classes)

In [14]:
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [15]:
#Creating the Model

model = Sequential()
model.add(Conv2D(64, (3, 3), input_shape=(28, 28, 1), activation='relu'))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(Flatten())
model.add(Dense(number_of_classes, activation='softmax'))

In [17]:
#Compiling the model

model.compile(loss='categorical_crossentropy', optimizer="Adam", metrics=['accuracy'])

In [19]:
#Fitting the model

model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=5, batch_size=32)

Epoch 1/5
1875/1875 [==============================] - 62s 32ms/step - loss: 0.2556 - accuracy: 0.9523 - val_loss: 0.0838 - val_accuracy: 0.9724
Epoch 2/5
1875/1875 [==============================] - 62s 33ms/step - loss: 0.0667 - accuracy: 0.9796 - val_loss: 0.0707 - val_accuracy: 0.9800
Epoch 3/5
1875/1875 [==============================] - 62s 33ms/step - loss: 0.0470 - accuracy: 0.9852 - val_loss: 0.0831 - val_accuracy: 0.9772
Epoch 4/5
1875/1875 [==============================] - 63s 34ms/step - loss: 0.0378 - accuracy: 0.9883 - val_loss: 0.0827 - val_accuracy: 0.9779
Epoch 5/5
1875/1875 [==============================] - 63s 34ms/step - loss: 0.0268 - accuracy: 0.9916 - val_loss: 0.0892 - val_accuracy: 0.9801


In [20]:
#Observing the metrics

metrics = model.evaluate(x_test, y_test, verbose=0)
print("Metrics(Test loss & Test Accuracy):")
print(metrics)

Metrics(Test loss & Test Accuracy):
[0.08917373418807983, 0.9800999760627747]


In [21]:
#Predicting the output

prediction=model.predict(x_test[:4])
print(prediction)

1/1 [==============================] - 2s 2s/step
[[6.5064547e-12 2.0378995e-19 3.2220457e-09 5.0868419e-08 4.0067954e-17
  1.9725233e-15 1.7253322e-19 1.0000000e+00 8.8150032e-10 1.6188428e-09]
 [8.0614450e-16 1.2608304e-13 1.0000000e+00 2.6756696e-11 1.6554036e-20
  4.0206081e-16 5.4154420e-08 5.2959983e-20 6.0979701e-09 7.9945947e-23]
 [2.9220120e-12 9.9999762e-01 1.5539084e-06 7.2226714e-13 5.1077166e-07
  6.0828538e-09 8.4759234e-11 1.2848354e-08 3.5143577e-07 1.3000962e-13]
 [1.0000000e+00 3.9502194e-16 2.1440423e-12 1.3841404e-18 7.4285028e-17
  1.6126565e-14 4.0810860e-10 1.7762837e-16 4.4197751e-13 2.1143579e-14]]


In [22]:
import numpy as np
print(np.argmax(prediction,axis=1))
print(y_test[:4])

[7 2 1 0]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [23]:
#Saving the model

model.save('models/mnistCNN.h5')

In [2]:
#Taking images as input and checking results

from tensorflow.keras.models import load_model
model = load_model(r'C:\Users\SHIRISHA\project-checkpoint.ipynb')
from PIL import Image
import numpy as np

for index in range(4):
         img = Image.open('data/' + str(index) + '.png').convert("L")
         img = img.resize(28,28)
         im2arr = np.array(img)
         im2arr = im2arr.reshape(1,28,28,1)
            
         y_pred = model.predict(im2arr)
         print(y_pred)

OSError: Unable to open file (file signature not found)

In [1]:
import os