In [1]:
#importing necessary libraries

import numpy
import tensorflow
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.layers import Conv2D
from keras.optimizers import Adam
from keras.utils import np_utils

In [2]:
#load data

(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [3]:
print(x_train.shape)
print(x_test.shape)

(60000, 28, 28)
(10000, 28, 28)


In [4]:
#understanding the data

x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [5]:
y_train[0]

5

In [6]:
y_train.shape

(60000,)

In [7]:
x_test.shape

(10000, 28, 28)

In [8]:
#Reshaping the Dataset

x_train = x_train.reshape(60000, 28, 28, 1).astype('float32')
x_test = x_test.reshape(10000, 28, 28, 1).astype('float32')

In [9]:
#One-Hot Encoding

number_of_classes = 10
y_train = np_utils.to_categorical(y_train, number_of_classes)
y_test = np_utils.to_categorical(y_test, number_of_classes)

In [10]:
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [11]:
#Creating the Model

model = Sequential()
model.add(Conv2D(64, (3, 3), input_shape=(28, 28, 1), activation='relu'))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(Flatten())
model.add(Dense(number_of_classes, activation='softmax'))

In [12]:
#Compiling the model

model.compile(loss='categorical_crossentropy', optimizer="Adam", metrics=['accuracy'])

In [13]:
#Fitting the model

model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=1, batch_size=32)

1875/1875 [==============================] - 100s 53ms/step - loss: 0.2381 - accuracy: 0.9503 - val_loss: 0.0878 - val_accuracy: 0.9722


In [14]:
#Observing the metrics

metrics = model.evaluate(x_test, y_test, verbose=0)
print("Metrics(Test loss & Test Accuracy):")
print(metrics)

Metrics(Test loss & Test Accuracy):
[0.08775996416807175, 0.9721999764442444]


In [15]:
#Predicting the output

prediction=model.predict(x_test[:4])
print(prediction)

1/1 [==============================] - 0s 182ms/step
[[5.0611226e-07 1.0023567e-13 7.2327102e-06 4.9399467e-05 7.3030010e-13
  2.7285525e-09 3.1248059e-13 9.9994206e-01 2.8521100e-07 5.0116176e-07]
 [5.7345022e-09 1.0389820e-09 9.9999976e-01 1.5455001e-09 9.5447543e-13
  7.6174532e-13 2.2667260e-07 5.7396274e-15 4.3561246e-10 6.2697646e-15]
 [3.8098758e-06 9.9825519e-01 3.0423570e-04 2.6747462e-05 2.7548935e-04
  1.6991597e-06 3.7201082e-06 1.7417435e-04 9.4995898e-04 5.0237345e-06]
 [9.9725807e-01 8.8474579e-09 2.3000960e-03 1.5741458e-05 5.1110587e-06
  6.0457282e-05 3.4285666e-04 2.8398250e-07 3.0187516e-07 1.7111261e-05]]


In [16]:
import numpy as np
print(np.argmax(prediction,axis=1))
print(y_test[:4])

[7 2 1 0]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [17]:
#Saving the model

model.save('models/mnistCNN.h5')

In [18]:
#Taking images as input and checking results

from tensorflow.keras.models import load_model
model = load_model(r'C:\Users\SHIRISHA\mini project\models\mnistCNN.h5')


In [19]:
from PIL import Image
import numpy as np

In [23]:
img = Image.open('C:\projectinputimage.jpg').convert("L")  #convert image to monochrome

In [24]:
img = img.resize((28,28))  #resizing of input image

In [26]:
im2arr = np.array(img)   #converting to image
im2arr = im2arr.reshape(1,28,28,1)   #reshaping according to our requirement
    
#Predicting the Test set results
y_pred = model.predict(im2arr)   #predicting the results
print(y_pred)

1/1 [==============================] - 0s 126ms/step
[[0.07074998 0.11541948 0.1125207  0.07422511 0.09784345 0.1205858
  0.07356007 0.10922137 0.11733465 0.10853942]]
